version: '1.0.{build}'
image: Visual Studio 2017

before_build:
- nuget restore
- choco install opencover.portable
- choco install codecov
  
build:
  project: Synergy.Recruitment.sln
  verbosity: minimal
  
test_script:
  - cmd: dotnet test ./test/Synergy.Recruitment.Test/Synergy.Recruitment.Test.csproj -c Debug -l Appveyor /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
  - cmd: codecov -f ./tests/Synergy.Recruitment.Test/coverage.opencover.xml
